import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useForm } from "react-hook-form";
import axiosInstance from "../../helper/axios-instance";
import { useEffect, useState } from "react";
import Footer from "../../components/footer";

const RoundData = () => {
  const { handleSubmit, register } = useForm();

  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    if (JSON.parse(sessionStorage.getItem("User")).type === "ADMIN") {
      setIsAuthenticated(true);
    }
  }, []);

  const onSubmit = async (data) => {
    try {
      console.log(data);
      await axiosInstance.put("/admin/round_data", data);
    } catch {
      //Todo error anzeigen
    }
  };
  if (!isAuthenticated) {
    return <div>Keine Berechtigung</div>; //TODO Komponente
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.register}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className={styles.inputContainer}>
            <label>Bildname</label>
            <input
              type="text"
              className={styles.input}
              {...register("pictureName")}
            />
          </div>

          <hr />
          <div className={styles.inputContainer}>
            <label> Position X</label>
            <input
              type="text"
              className={styles.input}
              {...register("position.x")}
            />
          </div>
          <hr />

          <div className={styles.inputContainer}>
            <label> Position Y</label>
            <input
              type="text"
              className={styles.input}
              {...register("position.y")}
            />
          </div>
          <button id="buttonRegister" type="submit">
            Abschicken
          </button>
        </form>
      </main>

      <Footer></Footer>
    </div>
  );
};
export default RoundData;
