import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { useForm } from "react-hook-form";
import axiosInstance from "../../helper/axios-instance";

export default function RoundData() {
  const { handleSubmit, register } = useForm();

  const onSubmit = async (data) => {
    try {
      console.log(data);
      await axiosInstance.put("/admin/round_data", data);
    } catch {
      //Todo error anzeigen
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.register}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className={styles.inputContainer}>
            <label>Bildname</label>
            <input
              type="text"
              className={styles.input}
              {...register("pictureName")}
            />
          </div>

          <hr />
          <div className={styles.inputContainer}>
            <label> Position X</label>
            <input
              type="text"
              className={styles.input}
              {...register("position.x")}
            />
          </div>
          <hr />

          <div className={styles.inputContainer}>
            <label> Position Y</label>
            <input
              type="text"
              className={styles.input}
              {...register("position.y")}
            />
          </div>
          <button id="buttonRegister" type="submit">
            Abschicken
          </button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
