import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useForm } from "react-hook-form";
import axiosInstance from "../../common/axios-instance";
import { useEffect, useState } from "react";
import Footer from "../../components/footer";

const RoundData = () => {
  const { handleSubmit, register } = useForm();

  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    if (JSON.parse(sessionStorage.getItem("User")).type === "ADMIN") {
      setIsAuthenticated(true);
    }
  }, []);

  const onSubmit = async (data) => {
    try {
      var file = document.querySelector("#roundPicture");
      console.log(file.files[0]);
      const formData = new FormData();

      formData.append("file", file.files[0]);
      const response = await axiosInstance.put("/admin/round_file", formData);
      data.round.mediaFileId = response.data.id;
      data.round.name = file.files[0].name;
      await axiosInstance.put("/admin/round_data", data.round);
    } catch {
      //Todo error anzeigen
    }
  };
  if (!isAuthenticated) {
    return <div>Keine Berechtigung</div>; //TODO Komponente
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.register}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className={styles.inputContainer}>
            <input
              type={"file"}
              id="roundPicture"
              name="roundPicture"
              {...register("file")}
            />
          </div>

          <hr />
          <div className={styles.inputContainer}>
            <label> Position X</label>
            <input
              type="text"
              className={styles.input}
              {...register("round.position.x")}
            />
          </div>
          <hr />

          <div className={styles.inputContainer}>
            <label> Position Y</label>
            <input
              type="text"
              className={styles.input}
              {...register("round.position.y")}
            />
          </div>

          <hr />

          <div className={styles.inputContainer}>
            <label> Typ</label>
            <select
              name="type"
              className={styles.input}
              {...register("round.type")}
            >
              <option value="PUBG">PUBG</option>
              <option value="APEX_LEGENDS">APEX LEGENDS</option>
            </select>
          </div>

          <hr />

          <button id="buttonRegister" type="submit">
            Abschicken
          </button>
        </form>
      </main>

      <Footer></Footer>
    </div>
  );
};
export default RoundData;
