import Head from "next/head";
import ProfileBar from "../components/profile-bar";
import Footer from "../components/footer";
import styles from "../styles/Home.module.css";

export default function DefaultLayout({ children }) {
    return (
            <>
                <Head>
                    <title>Home</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <ProfileBar/>
                    {children}
                </main>

                <Footer/>
            </>
    )
}