import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import LoadingIndicator from "../components/loading-indicator";
import axiosInstance from "../helper/axios-instance";
import ProfileBar from "../components/profile-bar";

export default function Game() {
  const [user, setUser] = useState();
  const [game, setGame] = useState();
  const [imagePath, setImagePath] = useState();

  const [isLoading, setIsLoading] = useState(true);

  const [round, setRound] = useState(0);
  const [gameOver, setGameOver] = useState(false);

  useEffect(() => {
    const id = JSON.parse(sessionStorage.getItem("User"))?.id;
    axiosInstance.get(`/user/${id}`).then((response) => setUser(response.data));
  }, []);

  useEffect(() => {
    if (user && game) {
      setIsLoading(false);
    }
  }, [user, game]);

  useEffect(() => {
    axiosInstance.get("/game", { params: { rounds: 5 } }).then((response) => {
      setGame(response.data);
      setImagePath("/images/" + response.data[0].pictureName + ".png");
    });
  }, []);

  function handleClick(event) {
    if (round + 1 < game.length) {
      setRound(round + 1);
      let userPosition = calculateCoordinates(event);
      let distance = calculateDistance(
        userPosition[0],
        userPosition[1],
        game[round].position.x,
        game[round].position.y
      );
      document.querySelector("#roundOutput").innerHTML =
        "Round " + (round + 2) + " / " + game.length;
      document.querySelector("#distanceOutput").innerHTML =
        "Distance: " + distance + "m";
      setImagePath("/images/" + game[round + 1].pictureName + ".png");
    } else if (!gameOver) {
      let userPosition = calculateCoordinates(event);
      let distance = calculateDistance(
        userPosition[0],
        userPosition[1],
        game[round].position.x,
        game[round].position.y
      );
      //console.log(distance);
      document.querySelector("#distanceOutput").innerHTML =
        "Distance: " + distance + "m";
      setGameOver(true);
    }
  }

  function calculateDistance(x1, y1, x2, y2) {
    return Math.round(
      Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2)) * 1000
    );
  }

  function calculateCoordinates(event) {
    let mouseX = event.clientX;
    let mouseY = event.clientY;
    let rect = document.querySelector("#mapImage").getBoundingClientRect();

    let x = ((mouseX - rect.left) / rect.width) * 8;
    let y = 8 - ((mouseY - rect.top) / rect.height) * 8;

    return [x, y];
  }

  if (isLoading) {
    return <LoadingIndicator />;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ProfileBar user={user} />

        <div id="gameContainer">
          <hr></hr>
          <div id="mapContainer">
            <Image
              id="mapImage"
              src={"/map.png"}
              alt="map"
              width={1384}
              height={1384}
              onClick={handleClick}
            />
          </div>
          <div id="infoContainer">
            <p id="roundOutput">Round 1 / {game.length}</p>
            <p id="distanceOutput">Distance: 0m</p>
            <div>
              <Image
                id="locationImage"
                src={imagePath}
                alt="location"
                width={2560}
                height={1440}
              />
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
