import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LogoutButton from "../components/logoutButton";

export default function Home() {

  let rounds = 10;

  function handleChange(event) {
    rounds = event.target.value;
    console.log("change", rounds);
    document.getElementById("outputRounds").innerHTML = "Rounds: " + rounds;
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Moinsen
        <div id="headContainer">
          <input id="searchUser" placeholder="Search for user..."></input>

          <div id="userContainer">
            <LogoutButton />
            <p id="username">
              Username
            </p>
            <div id="userImageContainer">
              <Image
                id="userImage"
                style={{
                  borderTopRightRadius: 25,
                  borderBottomRightRadius: 25,
                  borderBottomLeftRadius: 25,
                  borderTopLeftRadius: 25,
                }}
                src="/pepe.jpg"
                alt="pepe"
                width={50}
                height={50}
            />
            </div>
          </div>
        </div>
        <div id="buttonContainer">
          <hr></hr>
          <button className={styles.homeButtons}></button>
          <button className={styles.homeButtons}></button>
          <button className={styles.homeButtons}></button>
        </div>

        <div id="sliderContainer">
              <input type={"range"} min={"1"} max={"21"} defaultValue={11} id="sliderRounds" 
              onChange={handleChange} />
        </div>
        <span id="outputRounds">Rounds: 10</span>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
