import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useForm } from "react-hook-form";
import axiosInstance from "../common/axios-instance";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Register() {
    const router = useRouter();

    useEffect( () => {
        if ( sessionStorage.getItem( "User" ) ) {
            router.push( "/home" );
        }
    }, [] );

    const {
        register,
        handleSubmit,
        formState: { errors }
    } = useForm();

    const onSubmit = async ( data ) => {
        try {
            const response = await axiosInstance.post( "/login", data );

            sessionStorage.setItem( "User", JSON.stringify( response.data ) );
            location.href = "/home";
        } catch ( error ) {
            //Error-Handling
        }
    };
    return (
            <div className={ styles.container }>
                <Head>
                    <title>Log in</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={ styles.register }>
                    <div>
                        <div>
                            <form onSubmit={ handleSubmit( onSubmit ) }>
                                <div className={ styles.inputContainer }>
                                    <div className={ styles.logInRegisterHeader }>Log in</div>
                                    <label>Username / Email</label>
                                    <input
                                            className={ styles.input }
                                            type={ "text" }
                                            { ...register( "username", {
                                                required: {
                                                    value: true,
                                                    message: "Username must not be empty!"
                                                },
                                                minLength: {
                                                    value: 3,
                                                    message:
                                                            "Username has to be at least 3 characters long!"
                                                }
                                            } ) }
                                    />
                                    { errors.username && <p>{ errors.username.message }</p> }
                                </div>

                                <hr></hr>

                                <div className={ styles.inputContainer }>
                                    <label>Password</label>
                                    <input
                                            className={ styles.input }
                                            type={ "password" }
                                            { ...register( "password", {
                                                required: {
                                                    value: true,
                                                    message: "Password must not be empty!"
                                                },
                                                minLength: {
                                                    value: 4,
                                                    message:
                                                            "Password has to be at least 4 characters long!"
                                                }
                                            } ) }
                                    />
                                    { errors.password && <p>{ errors.password.message }</p> }
                                </div>

                                <hr></hr>

                                <button id="buttonRegister" type="submit">
                                    Log in
                                </button>
                            </form>
                        </div>
                    </div>
                </main>
            </div>
    );
}
