import Head from "next/head";
import Image from "next/image";
import axiosInstance from "../helper/axios-instance";
import styles from "../styles/Home.module.css";
import LogoutButton from "../components/logoutButton";
import { useState, useEffect } from "react";
import LoadingIndicator from "../components/loading-indicator";

function Profile() {
  const [user, setUser] = useState();

  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const id = JSON.parse(sessionStorage.getItem("User"))?.id;
    axiosInstance.get(`/user/${id}`).then((response) => setUser(response.data));
  }, []);

  useEffect(() => {
    if (user) {
      setIsLoading(false);
    }
  }, [user]);

  if (isLoading) {
    return <LoadingIndicator />;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id="headContainer">
          <div id="profileHeadContainer">
            <Image
              id="profileUserImage"
              style={{
                borderTopRightRadius: 10,
                borderBottomRightRadius: 10,
                borderBottomLeftRadius: 10,
                borderTopLeftRadius: 10,
              }}
              src="/pepe.jpg"
              alt="pepe"
              width={200}
              height={200}
            />

            <div id="profileUsernameContainer">
              <p id="profileUsername">{user.username}</p>
            </div>
            <div id="regInfoContainer">
              <p id="regInfo">Registered since: 09.11.2001</p>
            </div>
            <button id="deleteButton">Delete Account</button>
          </div>

          <div id="userContainer">
            <LogoutButton />
            <p id="username">{user.username}</p>
            <div id="userImageContainer">
              <Image
                id="userImage"
                style={{
                  borderTopRightRadius: 25,
                  borderBottomRightRadius: 25,
                  borderBottomLeftRadius: 25,
                  borderTopLeftRadius: 25,
                }}
                src="/pepe.jpg"
                alt="pepe"
                width={50}
                height={50}
              />
            </div>
          </div>
        </div>
        <div id="profileBodyContainer">
          <hr></hr>
          <div id="descriptionContainer">{user.description}</div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default Profile;
