import Head from "next/head";
import Image from "next/image";
import axiosInstance from "../helper/axios-instance";
import styles from "../styles/Home.module.css";
import Footer from "../components/footer";
import { useState, useEffect } from "react";
import LoadingIndicator from "../components/loading-indicator";
import ProfileBar from "../components/profile-bar";

function Profile() {
  const [user, setUser] = useState();

  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const id = JSON.parse(sessionStorage.getItem("User"))?.id;
    axiosInstance.get(`/user/${id}`).then((response) => setUser(response.data));
  }, []);

  useEffect(() => {
    if (user) {
      setIsLoading(false);
    }
  }, [user]);

  if (isLoading) {
    return <LoadingIndicator />;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id="headContainer">
          <div id="profileHeadContainer">
            <Image
              id="profileUserImage"
              style={{
                borderTopRightRadius: 10,
                borderBottomRightRadius: 10,
                borderBottomLeftRadius: 10,
                borderTopLeftRadius: 10,
              }}
              src="/pepe.jpg"
              alt="pepe"
              width={200}
              height={200}
            />

            <div id="profileUsernameContainer">
              <p id="profileUsername">{user.username}</p>
            </div>
            <div id="regInfoContainer">
              <p id="regInfo">Registered since: 09.11.2001</p>
            </div>
            <button id="deleteButton">Delete Account</button>
          </div>

          <ProfileBar user={user} />
        </div>
        <div id="profileBodyContainer">
          <hr />
          <div id="descriptionContainer">{user.description}</div>
          <div id="listContainer">
            <li className={styles.profileList}>Best score (Modus 1):</li>
            <li className={styles.profileList}>Best score (Modus 2):</li>
            <li className={styles.profileList}>Best score (Modus 3):</li>
            <br></br>
            <li className={styles.profileList}>Games played (Modus 1):</li>
            <li className={styles.profileList}>Games played (Modus 2):</li>
            <li className={styles.profileList}>Games played (Modus 3):</li>
            <li className={styles.profileList}>Games played (total):</li>
          </div>
          <div id="listValueContainer">
            <p className={styles.listValues}>1234</p>
            <p className={styles.listValues}>1234</p>
            <p className={styles.listValues}>1234</p>
            <br></br>
            <p className={styles.listValues}>1234</p>
            <p className={styles.listValues}>1234</p>
            <p className={styles.listValues}>1234</p>
            <p className={styles.listValues}>1234</p>
          </div>
        </div>
      </main>

      <Footer></Footer>
    </div>
  );
}

export default Profile;
