import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Register() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form
          action={process.env.NEXT_PUBLIC_API_URL + "/user/create"}
          method="post"
        >
          <h1>Register</h1>
          <p>Please fill in this form to create an account.</p>

          <hr />

          <b>Username</b>
          <input className={styles.input}
            type="text"
            placeholder="Enter Username"
            name="username"
            id="username"
            required
          />

          <hr />

          <b>Email</b>
          <input className={styles.input}
            type="text"
            placeholder="Enter Email"
            name="email"
            id="email"
            required
          />

          <hr />

          <b>Password</b>
          <input className={styles.input}
            type="password"
            placeholder="Enter Password"
            name="psw"
            id="psw"
            required
          />

          <hr />

          <b>Confirm Password</b>
          <input className={styles.input}
            type="password"
            placeholder="Confirm Password"
            name="pswConfirm"
            id="pswConfirm"
            required
          />

          <hr />

          <p>
            By creating an account you agree to our{" "}
            <a href="#">Terms & Privacy</a>.
          </p>
          <button type="submit" id="buttonRegister">Register</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
